Add controllers
Ksenni888/java-shareit pull request #1
Opened 2023-10-27 19:03 UTC by Ksenni888

2023-10-28 05:50 UTC, kalitva requested changes

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
Давай вместо `@Data` использовать
```
@Getter
@Setter
```

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Status.java
> +public enum Status {
Уточни в названии статус чего конкретно

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/Status.java
> +    Status() {
Такой конструктор есть по дефолту

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final Logger log = LoggerFactory.getLogger(ItemController.class);
Статические поля обычно объявляются перед инстанс полями

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        );
Пользуйся сеттерами если конструктор принимает больше чем три параметра. Можешь еще взглянуть аннотацию `@Builder` ломбока https://projectlombok.org/features/Builder

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final ItemMapper itemMapper;
Все маппинги должны быть в сервисе

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final UserRepository userService;
Репозитории нельзя инжектить друг в друга, ну и название поля поправь

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        if (!userService.containsUser(userId)) {
Это надо проверять в сервисе, не здесь

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +            throw new ObjectNotFoundException("This item not found");
То же, в сервисе

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        }
Все эти проверки - в сервисе

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        return itemsDto.values().stream().filter(x -> x.getName().toLowerCase().contains(text.toLowerCase()) || x.getDescription().toLowerCase().contains(text.toLowerCase()) && (x.getAvailable().equa
`x.getAvailable().equals(true) --> x.getAvailable()`

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    public long incrementId() {
private

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(String name, String description, boolean available, Long aLong) {
Не понял, зачем этот конструктор?

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/User.java
> +    public User() {
Используй `@NoArgsConstructor` ломбока

2023-10-28 05:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (userRepository.getAll().stream().filter(x -> x.getEmail().equals(user.getEmail())).count() != 0) {
Создай в репозитории метод `existsByEmail` , который будет возвращать `boolean` и вынеси туда это выражение

2023-10-30 10:11 UTC, Ksenni888 commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        }
Я не могу эти проверки перенести в сервис, тут идет обновление только тех строчек, котрые указаны пользователем, остальные оставляем как есть.  Например, запрос может быть: 
{"name" : "name1"}  и все, ни описание, ни доступность аренды не заданы -> меняем только имя.

2023-10-30 11:43 UTC, Ksenni888 commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final ItemMapper itemMapper;
Подскажи, пожалуйста, где можно почитать о том, как все эти слои выстраивать и что где должно находится, я теряюсь. Думала именно в репозитории надо превращать один объект в другой и хранить там же их.

2023-10-30 17:58 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        }
Не понял в чем проблема, но это точно нужно в сервисе делать, обязательно. Тем более, как я писал выше, репозитории не могу иметь дело с дто, это обязательное требование

2023-10-30 18:01 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(String name, String description, boolean available, Long aLong) {
Вообще конструтор должен при этом инициализировать свои поля параметрами) Но давай лучше обойдемся без него (заполним значения билдером или сеттерами)

2023-10-31 18:37 UTC, kalitva requested changes

2023-10-31 18:37 UTC, kalitva commented on pom.xml
> +            <artifactId>kotlin-stdlib</artifactId>
Это зачем?

2023-10-31 18:37 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto update(@RequestHeader("X-Sharer-User-Id") long userId, @RequestBody ItemDto itemDto, @PathVariable long itemId) {
Давай вынесем `"X-Sharer-User-Id"` в константу

2023-10-31 18:37 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        return items.values().stream().filter(x -> x.getOwner().getId() == userId).collect(Collectors.toList());
Форматируй стримы таким образом
```java
return items.values().stream()
        .filter(x -> x.getOwner().getId() == userId)
        .collect(Collectors.toList());
```

2023-10-31 18:37 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemRepository.findById(userId, itemId) == null) {
Проверяй наличие айтема вызовом `containsItem`

2023-10-31 18:37 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    public boolean existsByEmail(User user) {
Принимай в параметре метода строку, а не целый объект юзера

2023-11-03 07:29 UTC, kalitva approved these changes

2023-11-03 07:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> findItems(@RequestHeader("X-Sharer-User-Id") long userId, @RequestParam(defaultValue = "Write the text") String text) {
Убери `defaultValue`, поставь `requesred = false` на search

2023-11-03 07:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (userRepository.getAll().stream().anyMatch(x -> (x.getEmail().equals(user.getEmail())) && (userId != x.getId()))) {
Создай метод в репозитории `conttainsUser` и вызывай его здесь вместо этого выражения

2023-11-08 10:55 UTC, merged